// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PeopleIncApi.Data;

#nullable disable

namespace PeopleIncApi.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PeopleIncApi.Models.Pessoa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Pessoa", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 54L,
                            Email = "Kennedy68@yahoo.com",
                            Idade = 55,
                            Nome = "Maxine"
                        },
                        new
                        {
                            Id = 4L,
                            Email = "Kory47@yahoo.com",
                            Idade = 53,
                            Nome = "Keara"
                        },
                        new
                        {
                            Id = 29L,
                            Email = "Adele.VonRueden80@yahoo.com",
                            Idade = 49,
                            Nome = "Cecelia"
                        },
                        new
                        {
                            Id = 87L,
                            Email = "Amaya.Muller@gmail.com",
                            Idade = 33,
                            Nome = "Arch"
                        },
                        new
                        {
                            Id = 99L,
                            Email = "Earline2@gmail.com",
                            Idade = 46,
                            Nome = "Ford"
                        },
                        new
                        {
                            Id = 12L,
                            Email = "Lonnie_Schultz@yahoo.com",
                            Idade = 39,
                            Nome = "Dedric"
                        },
                        new
                        {
                            Id = 95L,
                            Email = "Delbert_Sauer53@hotmail.com",
                            Idade = 29,
                            Nome = "Dandre"
                        },
                        new
                        {
                            Id = 51L,
                            Email = "Kasey_Pfannerstill62@yahoo.com",
                            Idade = 37,
                            Nome = "Alessandra"
                        },
                        new
                        {
                            Id = 93L,
                            Email = "Rasheed_Koss48@gmail.com",
                            Idade = 38,
                            Nome = "Jordi"
                        },
                        new
                        {
                            Id = 79L,
                            Email = "Barry.Friesen34@yahoo.com",
                            Idade = 41,
                            Nome = "Rodolfo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
